#! /bin/bash

clear
echo -e '\n <setup> \n'

read -rep $'\t<input email=willem.bressers@axians.com\>' email; email=${email:-"willem.bressers@axians.com"}
read -rep $'\t<input name=Willem Bressers\>' name; name=${name:-"Willem Bressers"}

# =============================================================================
# Shared (VBOX setup)
# =============================================================================
if [ ! -d /media/sf_shared ]; then
	echo -e '\t<shared_folder>'

	# Open VirtualBox
	# Right-click your VM, then click **Settings**
	# Go to **Shared Folders** section
	# Add a new shared folder
	# On **Add Share** prompt, select the **Folder Path** in your host that you want to be accessible inside your VM.
	# In the **Folder Name** field, type `shared`
	# Uncheck **Read-only** and **Auto-mount**, and check **Make Permanent**
	# Start your VM
	# Once your VM is up and running, go to **Devices** menu -> **Insert Guest Additions CD image menu**
	# create the mount directory
	sudo mkdir /media/cdrom
	# Use the following command to mount the CD:
	sudo mount /dev/cdrom /media/cdrom
	# Install dependencies for VirtualBox guest additions:
	sudo apt update
	sudo apt install -y build-essential linux-headers-$(uname -r)
	# Run installation script for the guest additions:
	sudo /media/cdrom/VBoxLinuxAdditions.run

	sudo usermod -aG vboxsf $(whoami)

	echo -e '\t</shared_folder>'
	shutdown -r now
fi

# =============================================================================
# Ssh
# =============================================================================
if [ ! -f ~/.ssh/id_rsa.pub ]; then
	echo -e '\t<ssh_key>'

	# Generate an ssh key
	ssh-keygen -t rsa -b 4096 -C $email
	
	echo -e '\t</ssh_key>'
fi 

# =============================================================================
# Projects
# =============================================================================
if [ ! -d ~/projects ]; then
	echo -e '\t<project_folder>'

	# Create a symbolic link to the shared folder
	sudo ln -s /media/sf_shared/projects ~/projects
	
	echo -e '\t</project_folder>'
fi

# =============================================================================
# Git
# =============================================================================
if [ ! -f ~/.gitignore ]; then
	echo -e '\t<git>'

	# create a .gitignore file
	touch ~/.gitignore

	# specify some global git settings
	git config --global user.email $email
	git config --global user.name $name
	git config --global push.default simple
	git config --global core.excludesfile ~/.gitignore

	echo -e '\t</git>'
fi

# =============================================================================
# Python
# =============================================================================
if [ ! -d $HOME/.virtualenvs ]; then
	echo -e '\t<python3_virtualenv>'

	# Install pip3
	sudo apt install -y python3-pip

	# install python libraries
	sudo pip3 install virtualenv virtualenvwrapper

	# update our  ~/.bashrc  file
	echo -e "\n# virtualenv and virtualenvwrapper" >> ~/.bashrc
	echo "export WORKON_HOME=$HOME/.virtualenvs" >> ~/.bashrc
	echo "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3" >> ~/.bashrc
	echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bashrc

	echo -e '\t</python3_virtualenv>'
fi

# =============================================================================
# Bash
# =============================================================================
sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ~/.bashrc
source ~/.bashrc

echo -e '\n </setup> \n'
